name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Export Image Version
        run: echo "ANSIBLE_VERSION=$(cat requirements.txt | grep -iE "^ansible\s*==" | awk '{split($0,a,"=="); print a[2]}')" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} \
            --progress=plain \
            -t asuprun/ansible:${ANSIBLE_VERSION} \
            -t asuprun/ansible:latest \
            .

      - name: Push Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            --progress=plain \
            --push \
            -t asuprun/ansible:${ANSIBLE_VERSION} \
            -t asuprun/ansible:latest \
            .
